### ISSUE TITLE
Serviceworker not registered under root

### ISSUE THREAD

**Issue by joshin2017** [vsanse/plugin_sg_pwa#1]
![image](https://user-images.githubusercontent.com/28758258/73736194-67af4f00-4766-11ea-9496-78b5a65b8921.png)

After installing plugin the scope of serviceworker is domainname.com/serviceworker/
Please find attached screenshot.

Is there any change we need to do?

**Comment by vsanse** [comment]
Looks like you have missed step 2 in setup or haven't configured properly.

**Comment by joshin2017** [comment]
Thank you team.
Step 2: Pipeline urls. I had to uncheck trailing slash for serviceworker.
The issue is solved.
